Feat: #156 오픈채팅방 정보 조회(for user) API 추가
Genti2024/GenTI-BE pull request #157
Opened 2024-09-10 12:07 UTC by LeeJae-H

2024-09-10 23:52 UTC, BYEONGRYEOL requested changes
말이 좀 많았네요 논의할것있으면 디코로 말씀해주세영

2024-09-10 23:52 UTC, BYEONGRYEOL commented on genti-api/src/main/java/com/gt/genti/openchat/api/AdminOpenChatApi.java
> +        @RequestHeader(value = "Open-Chat-Secret-Key") String secretKey,
@RequestHeader(value = "Open-Chat-Secret-Key") String secretKey <- http 헤더 key값이 유저의 오픈채팅방 접속 비밀키인지, 어드민이 오픈채팅방 도메인을 관리할 수 있는 키인지 명확하지 않아서 Admin-Secret-Key 와 같이 적용하는건 어떠신가요?

2024-09-10 23:52 UTC, BYEONGRYEOL commented on genti-api/src/main/java/com/gt/genti/openchat/api/AdminOpenChatApi.java
> +        @RequestParam(required = false) String url
url은 백엔드에서 직접관리하는걸로 가기로했던 것 같은데 변동이 있으셨다면 말씀해주세용

2024-09-10 23:52 UTC, BYEONGRYEOL commented on genti-api/src/main/java/com/gt/genti/openchat/service/OpenChatService.java
> +            throw ExpectedException.withLogging(ResponseCode.InvalidBirthYearFormat, birthYear);
예외 발생 보다는 차라리 '오픈채팅방 접근불가' 로 응답하는 것이 안정성 측면에서 좋아보입니다. 
+ NumberFormatExeption 보다는 NPE가 발생할 확률이 높다고 생각해서요,(생년월일값은 앱단에서 직접 입력 불가임),
``` java
catch (NumberFormatException nfe | NullPointerException npe) 
```

꼴로 변경하면 어떨까 합니다.

2024-09-10 23:52 UTC, BYEONGRYEOL commented on genti-api/src/main/java/com/gt/genti/openchat/controller/AdminOpenChatController.java
> +        @RequestHeader(value = "Open-Chat-Secret-Key") String secretKey,
이 Http Header를 허용하는지 SecurityConfig에서 설정되어있는지 확인이 필요합니다. 
.allowHeaders() 등의 메서드로 정의해두거든요

2024-09-10 23:52 UTC, BYEONGRYEOL commented on genti-api/src/main/java/com/gt/genti/openchat/controller/AdminOpenChatController.java
> +        @RequestParam(required = false) String url
admin이 url은 변경하지않기로했던것같은데 변경됐을까요?

2024-09-11 11:08 UTC, LeeJae-H commented on genti-api/src/main/java/com/gt/genti/openchat/api/AdminOpenChatApi.java
> +        @RequestHeader(value = "Open-Chat-Secret-Key") String secretKey,
네 그게 더 명확하네요!

2024-09-11 11:08 UTC, LeeJae-H commented on genti-api/src/main/java/com/gt/genti/openchat/api/AdminOpenChatApi.java
> +        @RequestParam(required = false) String url
count만 변경하는 것이 맞습니다 
수정하겠습니다

2024-09-11 11:08 UTC, LeeJae-H commented on genti-api/src/main/java/com/gt/genti/openchat/controller/AdminOpenChatController.java
> +        @RequestHeader(value = "Open-Chat-Secret-Key") String secretKey,
확인했습니다

2024-09-11 11:08 UTC, LeeJae-H commented on genti-api/src/main/java/com/gt/genti/openchat/controller/AdminOpenChatController.java
> +        @RequestParam(required = false) String url
아닙니다
count만 변경하도록 수정하겠습니다

2024-09-11 11:08 UTC, LeeJae-H commented on genti-api/src/main/java/com/gt/genti/openchat/service/OpenChatService.java
> +            throw ExpectedException.withLogging(ResponseCode.InvalidBirthYearFormat, birthYear);
catch (NumberFormatException nfe | NullPointerException npe) 
이 부분에 동의합니다.

혹시 
"예외 발생 보다는 차라리 '오픈채팅방 접근불가' 로 응답하는 것이 안정성 측면에서 좋아보입니다."
이 부분에서, 어떤 응답 형식으로 전달하는 걸 말씀하시는건가요?!

2024-09-11 11:15 UTC, BYEONGRYEOL commented
추가 답변 달았습니다

2024-09-11 11:16 UTC, BYEONGRYEOL requested changes
답변달았습니다

2024-09-11 11:16 UTC, BYEONGRYEOL commented on genti-api/src/main/java/com/gt/genti/openchat/controller/AdminOpenChatController.java
> +@RequestMapping("/api/v1/open-chat")
이 api 인증 없이 실행할 수 있어보이지않아서, /auth를 securityWhiteList에 추가했던 것 처럼 수정이 필요해보입니다

2024-09-11 11:16 UTC, BYEONGRYEOL commented on genti-api/src/main/java/com/gt/genti/openchat/service/OpenChatService.java
> +            throw ExpectedException.withLogging(ResponseCode.InvalidBirthYearFormat, birthYear);
그냥 1974~2003년생? 원래 OB,YB에도 속하지 않는 사람이 받는 응답과 동일한거죠, 프론트에서 애초에 오픈채팅방으로 넘어가는 뷰를 보이지 않도록 응답하는걸 생각했습니다

2024-09-11 11:18 UTC, LeeJae-H commented on genti-api/src/main/java/com/gt/genti/openchat/service/OpenChatService.java
> +            throw ExpectedException.withLogging(ResponseCode.InvalidBirthYearFormat, birthYear);
엇 근데 위의 에러(nfe, npe)가 발생하면, 사용자의 생년 데이터에 문제가 있다는 것인데 
에러를 던져야 확인할 수 있지 않을까요?!

2024-09-11 11:22 UTC, BYEONGRYEOL commented on genti-api/src/main/java/com/gt/genti/openchat/service/OpenChatService.java
> +            throw ExpectedException.withLogging(ResponseCode.InvalidBirthYearFormat, birthYear);
사진생성 완료 후 별점매기고 나서의 action에 대해서 오류가 발생했다는 팝업이 나오기보단, 아예 오픈채팅관련한 얘기가 안나오는게 유저 입장에서 만족스러울것으로 생각이들거든요 생년 데이터가 잘못될 수 있는 여지가 사실 없기도 하고요, 또 유저 생년데이터가 잘못되었을때 그걸 수정하도록 유도하는 등의 뷰가 전혀 없기도 해서요

약간 알면 어쩔꺼냐? 라는 문제가 있고,
백엔드에서 직접 db 건드려서 예방할 수 있다는 것도 있어서 위와같이 생각했습니다

2024-09-11 12:05 UTC, LeeJae-H commented on genti-api/src/main/java/com/gt/genti/openchat/service/OpenChatService.java
> +            throw ExpectedException.withLogging(ResponseCode.InvalidBirthYearFormat, birthYear);
아 
"사진생성 완료 후 별점매기고 나서의 action에 대해서 오류가 발생했다는 팝업이 나오기보단, 아예 오픈채팅관련한 얘기가 안나오는게 유저 입장에서 만족스러울것으로 생각이들거든요" 
이 부분에서 확실히 이해했습니다!
바로 수정하겠습니다

2024-09-11 12:11 UTC, LeeJae-H commented on genti-api/src/main/java/com/gt/genti/openchat/service/OpenChatService.java
> +            throw ExpectedException.withLogging(ResponseCode.InvalidBirthYearFormat, birthYear);
catch (NumberFormatException nfe | NullPointerException npe) 
이 부분에서
"NumberFormatException과 NullPointerException은 둘 다 RuntimeException을 상속받는 예외입니다. 따라서 멀티 캐치로 사용할 수 있습니다. 그러나 멀티 캐치 블록에서는 예외 변수는 하나만 선언해야 합니다."라고 하는군요.

따라서 
catch (NumberFormatException | NullPointerException e)
이렇게 변경했습니다

2024-09-11 12:20 UTC, LeeJae-H commented on genti-api/src/main/java/com/gt/genti/openchat/service/OpenChatService.java
> +            return 2000;
이거 괜찮을까요..?
좋은 방법이 생각나지 않는군요..

2024-09-11 13:04 UTC, BYEONGRYEOL requested changes
고생많으십니당..

2024-09-11 13:04 UTC, BYEONGRYEOL commented on genti-api/src/main/java/com/gt/genti/openchat/service/OpenChatService.java
> +            return 2000;
필요하면 log.info / log.error로 상황 전달하는거 추가하면 될것같고 저는 info정도만 찍어두면 되지 않을까 싶습니당

2024-09-11 13:04 UTC, BYEONGRYEOL commented on genti-api/src/main/java/com/gt/genti/openchat/service/OpenChatService.java
> +            return 2000;
쪼끔더 좋은방안은 parseBirthYear 메서드가 getOpenChatType 메서드 안에서 실행되고, try catch 구문 사용해서 parseBirthYear 메서드 실행간 무슨 예외라도 나면 OpenChatType.NONE으로 리턴되도록하면 좀 더 명료해보이긴합니당

2024-09-11 13:04 UTC, BYEONGRYEOL commented on genti-auth/src/main/java/com/gt/genti/config/SecurityConfig.java
> +		config.setAllowedHeaders(List.of("Authorization", "Cache-Control", "Content-Type", "Open-Chat-Secret-Key"));
요기는 Admin-Secret-Key 로 변경되어야할거같네요 혹시로컬에서 테스트 해보실 수 있을까요?

2024-09-12 07:53 UTC, LeeJae-H commented on genti-api/src/main/java/com/gt/genti/openchat/service/OpenChatService.java
> +            return 2000;
말씀하신대로 getOpenChatType 메서드 안에서 실행하는 것이 좋을것같군요

2024-09-12 14:23 UTC, merged