Feat: #33 별점 API 추가, Fix: #27 api endpoint 수정
Genti2024/GenTI-BE pull request #58
Opened 2024-07-18 03:28 UTC by LeeJae-H

2024-07-18 03:33 UTC, LeeJae-H commented
죄송합니다 간단한 API 하나 추가하는데 오래걸렸네요ㅠ

래리가 생각한 것과 비슷하게 구현한 것이면 좋겠습니다ㅠ 
내용은 적지만, 자비 없는 comment 부탁드립니다.

2024-07-18 03:41 UTC, LeeJae-H commented
아 참고로 로컬 db에서
ALTER TABLE picture_completed ADD COLUMN star INT CHECK (star >= 1 AND star <= 5);
위 ddl 실행했습니다

2024-07-18 04:02 UTC, BYEONGRYEOL commented
@LeeJae-H  2개 질문 있는데 답변 or 수정commit 진행해주십쇼 디코든 코멘트든 편하신대로요

2024-07-18 05:20 UTC, BYEONGRYEOL requested changes

2024-07-18 05:20 UTC, BYEONGRYEOL commented on genti-api/src/main/java/com/gt/genti/picture/controller/PictureController.java
> +	@PostMapping
마르가 말한거 수정해주셨네요 good

2024-07-18 05:20 UTC, BYEONGRYEOL commented on genti-api/src/main/java/com/gt/genti/picturegenerateresponse/controller/UserPGRESController.java
> +		@RequestParam(name = "star") Integer star) {
다 좋고, Controller 단의 Validation Annotation,
@NotNull, @Range(~~~) 를 사용하면 db보다 앞단에서 유효성검증을 수행할 수 있을 것으로 보입니다

2024-07-18 05:20 UTC, BYEONGRYEOL commented on genti-domain/src/main/java/com/gt/genti/picturegenerateresponse/model/PictureGenerateResponse.java
> +	@Column(name = "star")
mysql ddl문에 직접 유효값 범위를 명시하는 것 말고 
jpa entity <-> schema mapper 단에서 해당 유효값 범위설정을 수행하도록 할 수도 있나요?
(진짜 모름)
(모르는데 될것 같아서 여쭤보는 중입니다)

2024-07-18 13:03 UTC, LeeJae-H commented on genti-api/src/main/java/com/gt/genti/picturegenerateresponse/controller/UserPGRESController.java
> +		@RequestParam(name = "star") Integer star) {
넵
프론트에서 값을 강제해서 보내므로 서버에서는 유효성 검증을 수행할 필요가 없다고 생각해서 작성한 것인데,
서버에서도 유효성 검증을 해야겠네요!

2024-07-18 13:05 UTC, LeeJae-H commented on genti-domain/src/main/java/com/gt/genti/picturegenerateresponse/model/PictureGenerateResponse.java
> +	@Column(name = "star")
음..

@Column(name = "star")
@Min(1)
@Max(5)
Integer star;

제 생각은 이런 방식이 생각이 나는데 맞는 것인지는 잘 모르겠어요

그리고 ddl에 유효값 범위를 명시하는 것은 서버에서 검증을 하든 안하든 데이터베이스 무결성을 위해 명시해놓은 것입니다!

2024-07-18 13:25 UTC, LeeJae-H commented
그리고 디스코드 내용 확인했는데,
"별점 API를 쐈을때 해당유저를 NEW_REQUEST_AVAILABLE 상태로 만들어주는 로직 추가"
이거를 적용하면 되는 거 맞나요??

2024-07-18 13:27 UTC, LeeJae-H commented
그리고 디스코드 내용 확인했는데 최종 결론은,
"별점 API를 쐈을때 해당유저를 NEW_REQUEST_AVAILABLE 상태로 만들어주는 로직 추가"
이거를 적용하면 되는 거 맞나요??

2024-07-19 10:31 UTC, BYEONGRYEOL commented on genti-domain/src/main/java/com/gt/genti/picturegenerateresponse/model/PictureGenerateResponse.java
> +	@Column(name = "star")
넵  ddl에 유효값 범위를 명시하는 것은 서버에서 검증을 하든 안하든 데이터베이스 무결성을 위해 명시해놓은 것입니다!
확인했습니다. 
db에 못들어가는 예외라면 예외가 관리될 수 있도록 was 단에서도 해야한다고 생각해서 말씀드렸어요 
서로 합의된거 같습니당

2024-07-20 08:40 UTC, BYEONGRYEOL approved these changes
고생하셨어요 다음에 여유날 때 중복되는 
pictureGenerateResponseId -> 조회한 PGRES, PGREQ가 해당 요청자의 것이 맞는지 검증하는 로직은 private method로 추출해도되겠슴다 우선은.. ㄱㄱ

2024-07-20 08:41 UTC, merged